// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CListaAprobadores.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace PROYDOS {
  public static partial class CListaAprobadoresService
  {
    static readonly string __ServiceName = "CListaAprobadoresService";

    static readonly grpc::Marshaller<global::PROYDOS.GetCAprobadoresRequest> __Marshaller_GetCAprobadoresRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PROYDOS.GetCAprobadoresRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::PROYDOS.GetCAprobadoresResponse> __Marshaller_GetCAprobadoresResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PROYDOS.GetCAprobadoresResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::PROYDOS.GetCAprobadoresRequest, global::PROYDOS.GetCAprobadoresResponse> __Method_GetAprobadores = new grpc::Method<global::PROYDOS.GetCAprobadoresRequest, global::PROYDOS.GetCAprobadoresResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetAprobadores",
        __Marshaller_GetCAprobadoresRequest,
        __Marshaller_GetCAprobadoresResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PROYDOS.CListaAprobadoresReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CListaAprobadoresService</summary>
    [grpc::BindServiceMethod(typeof(CListaAprobadoresService), "BindService")]
    public abstract partial class CListaAprobadoresServiceBase
    {
      public virtual global::System.Threading.Tasks.Task GetAprobadores(global::PROYDOS.GetCAprobadoresRequest request, grpc::IServerStreamWriter<global::PROYDOS.GetCAprobadoresResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CListaAprobadoresService</summary>
    public partial class CListaAprobadoresServiceClient : grpc::ClientBase<CListaAprobadoresServiceClient>
    {
      /// <summary>Creates a new client for CListaAprobadoresService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CListaAprobadoresServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CListaAprobadoresService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CListaAprobadoresServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CListaAprobadoresServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CListaAprobadoresServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::PROYDOS.GetCAprobadoresResponse> GetAprobadores(global::PROYDOS.GetCAprobadoresRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAprobadores(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::PROYDOS.GetCAprobadoresResponse> GetAprobadores(global::PROYDOS.GetCAprobadoresRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetAprobadores, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CListaAprobadoresServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CListaAprobadoresServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CListaAprobadoresServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAprobadores, serviceImpl.GetAprobadores).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CListaAprobadoresServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAprobadores, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::PROYDOS.GetCAprobadoresRequest, global::PROYDOS.GetCAprobadoresResponse>(serviceImpl.GetAprobadores));
    }

  }
}
#endregion
